services:

  api:
    image: wesleymime/finances-api
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    entrypoint: [
      "java",
      "-Dspring.profiles.active=prod",
      "-DPOSTGRES_URL=db:5432/CHANGEDB",
      "-DPOSTGRES_USERNAME=CHANGEUSR",
      "-DPOSTGRES_PASSWORD=CHANGEPWD",
      "-DJWT_SECRET=CHANGEJWT",
      "-jar",
      "/app.jar"
    ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CHANGEDB
      POSTGRES_USER: CHANGEUSR
      POSTGRES_PASSWORD: CHANGEPWD