services:

  front-end:
    image: wesleymime/finances-front-end
    restart: always
    ports:
      - "80:4200"

  api:
    image: wesleymime/finances-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint: [
      "java",
      "-Dspring.profiles.active=prod",
      "-DPOSTGRES_URL=db:5432/CHANGEDB",
      "-DPOSTGRES_USERNAME=CHANGEUSR",
      "-DPOSTGRES_PASSWORD=CHANGEPWD",
      "-DJWT_SECRET=ME7SXkNLos9X6azj8/SMMLXxiq7Wg32PBzTNNohxZ+ykIwKVKMeWmtMwJNl6zhi8QgvcWCmjWu9m4fQagyW0IQ==",
      "-DREDIS_URL=redis",
      "-DAI_API_KEY=CHANGEKEY",
      "-jar",
      "/app.jar"
    ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CHANGEDB
      POSTGRES_USER: CHANGEUSR
      POSTGRES_PASSWORD: CHANGEPWD

  redis:
    image: redis
    ports:
      - "6379:6379"