finances:
    jwt:
        expiration: 1800000
        secret: ${JWT_SECRET:ME7SXkNLos9X6azj8/SMMLXxiq7Wg32PBzTNNohxZ+ykIwKVKMeWmtMwJNl6zhi8QgvcWCmjWu9m4fQagyW0IQ==}
spring:
    sql:
      init:
        mode: ALWAYS
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
