finances:
    jwt:
        expiration: 1800000
        secret: ${JWT_SECRET:oei43qyq3v2511ro5373qbtqhhaer353shes3arhqhq3rv238q57nv2q-35v2c}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_URL}
        username: ${POSTGRES_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
