name: Maven CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_test_deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container images
        run: docker compose -f docker-compose-dev.yml build

      - name: Tag Docker images
        run: |
          docker tag finances-api-api wesleymime/finances-api
          docker tag finances-api-front-end wesleymime/finances-front-end

      - name: Publish Docker image
        run: |
          docker push wesleymime/finances-api
          docker push wesleymime/finances-front-end